#https://devops.ifrn.edu.br/2018/08/16/crie-seu-micro-servico/
version: "3.3"
   
services:
  db-cookit:
    image: postgres:13
    restart: always
    tty: true
    environment:
      POSTGRES_DB: cookit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdatabase:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookit_backend_app
    restart: always
    depends_on:
      - db-cookit
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network

volumes:
  postgresdatabase:

#Docker Networks
networks:
  app-network:
    driver: bridge

